/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    members: Member;
    genres: Genre;
    occasions: Occasion;
    'member-roles': MemberRole;
    groups: Group;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    'member-roles': MemberRolesSelect<false> | MemberRolesSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    contact: Contact;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    contact: ContactSelect<false> | ContactSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  path: string;
  /**
   * Optional caption describing the image or performance
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  name: string;
  /**
   * Select the role/specialization for this member.
   */
  role: number | MemberRole;
  /**
   * Select the group this member belongs to.
   */
  group?: (number | null) | Group;
  image_path: string;
  socials?: {
    /**
     * Optional Facebook profile URL or handle
     */
    facebook?: string | null;
    /**
     * Optional Instagram profile URL or handle
     */
    instagram?: string | null;
  };
  /**
   * Toggle visibility on the landing page.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles".
 */
export interface MemberRole {
  id: number;
  /**
   * Name of the band member role or category.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Enable or disable this role.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  title: string;
  /**
   * Order of this group tab on the website (e.g. 1, 2, 3...). Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Select members and drag the handle (≡) to arrange their display order within this group.
   */
  members?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Search and select an icon from the catalog.
   */
  icon: string;
  /**
   * Select an ambient glow preset for the genre card.
   */
  accent:
    | 'from-amber-500/20 to-amber-700/10'
    | 'from-orange-500/20 to-amber-700/10'
    | 'from-emerald-500/20 to-teal-700/10'
    | 'from-yellow-500/20 to-amber-600/10'
    | 'from-purple-500/20 to-indigo-700/10'
    | 'from-blue-500/20 to-cyan-700/10'
    | 'from-amber-600/20 to-red-700/10'
    | 'from-rose-500/20 to-pink-700/10'
    | 'from-amber-400/25 to-yellow-600/10'
    | 'from-pink-500/20 to-rose-700/10'
    | 'from-red-500/25 to-amber-600/10'
    | 'from-violet-500/20 to-purple-800/10'
    | 'from-teal-500/20 to-cyan-800/10';
  /**
   * Order of display on the website (e.g. 1, 2, 3...). Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Toggle visibility on the landing page.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Search and select an occasion or performance icon.
   */
  icon: string;
  /**
   * Select an ambient glow preset for the occasion card.
   */
  accent:
    | 'from-amber-500/20 to-amber-700/10'
    | 'from-orange-500/20 to-amber-700/10'
    | 'from-emerald-500/20 to-teal-700/10'
    | 'from-yellow-500/20 to-amber-600/10'
    | 'from-purple-500/20 to-indigo-700/10'
    | 'from-blue-500/20 to-cyan-700/10'
    | 'from-amber-600/20 to-red-700/10'
    | 'from-rose-500/20 to-pink-700/10'
    | 'from-amber-400/25 to-yellow-600/10'
    | 'from-pink-500/20 to-rose-700/10'
    | 'from-red-500/25 to-amber-600/10'
    | 'from-violet-500/20 to-purple-800/10'
    | 'from-teal-500/20 to-cyan-800/10';
  bullets?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Order of display on the website (e.g. 1, 2, 3...). Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Toggle visibility on the landing page.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'member-roles';
        value: number | MemberRole;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  path?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  name?: T;
  role?: T;
  group?: T;
  image_path?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  icon?: T;
  accent?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  icon?: T;
  accent?: T;
  bullets?:
    | T
    | {
        point?: T;
        id?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles_select".
 */
export interface MemberRolesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Main phone number for inquiries and bookings
   */
  primaryPhone?: string | null;
  /**
   * Alternate phone number for event coordinators
   */
  secondaryPhone?: string | null;
  email?: string | null;
  address?: string | null;
  googleMapsUrl?: string | null;
  /**
   * Phone number linked to WhatsApp (with country code)
   */
  whatsappNumber?: string | null;
  /**
   * This message will be pre-filled automatically when visitors click the WhatsApp button
   */
  whatsappPrompt?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Main title tag used in search engines and browser tabs
   */
  title: string;
  /**
   * Brief summary of your band and site shown in search engine results
   */
  description: string;
  /**
   * Comma-separated keywords for search engine indexing
   */
  keywords?: string | null;
  brandName?: string | null;
  /**
   * Image preview displayed when your link is shared on Facebook, WhatsApp, Twitter, etc.
   */
  ogImage?: string | null;
  /**
   * Optional customized title specifically for social share cards
   */
  ogTitle?: string | null;
  /**
   * Optional customized description specifically for social share cards
   */
  ogDescription?: string | null;
  /**
   * Twitter @username used for twitter:site and twitter:creator metadata
   */
  twitterHandle?: string | null;
  twitterCard?: ('summary_large_image' | 'summary') | null;
  /**
   * Main introductory description displayed in the hero section below the band slogan.
   */
  heroDescription?: string | null;
  /**
   * Subtitle description displayed in Our Musical Expertise section.
   */
  genreDescription?: string | null;
  /**
   * Subtitle description displayed in Moments in Resonance (Gallery) section.
   */
  galleryDescription?: string | null;
  /**
   * Subtitle description displayed in Meet The Resonance (Members) section.
   */
  membersDescription?: string | null;
  /**
   * Subtitle description displayed in Music For Every Occasion section.
   */
  occasionsDescription?: string | null;
  /**
   * Subtitle description displayed in Let’s Connect (Contact) section.
   */
  contactDescription?: string | null;
  /**
   * Bio description displayed in the footer below the brand name.
   */
  footerDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  primaryPhone?: T;
  secondaryPhone?: T;
  email?: T;
  address?: T;
  googleMapsUrl?: T;
  whatsappNumber?: T;
  whatsappPrompt?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  keywords?: T;
  brandName?: T;
  ogImage?: T;
  ogTitle?: T;
  ogDescription?: T;
  twitterHandle?: T;
  twitterCard?: T;
  heroDescription?: T;
  genreDescription?: T;
  galleryDescription?: T;
  membersDescription?: T;
  occasionsDescription?: T;
  contactDescription?: T;
  footerDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}